FROM python:2.7-slim
MAINTAINER Chris Dean "cdean11@colostate.edu"

LABEL org.label-schema.build-date="2018-01-20T18:31:22Z" \
      org.label-schema.name="AUIR" \
      org.label-schema.description="A Docker image for Python" \
      org.label-schema.url="https://github.com/cdeanj/auir" \
      org.label-schema.vcs-ref="71f505cbdd9a4501ecbc2a39b2352ddca7b37fb7" \
      org.label-schema.vcs-url="https://github.com/cdeanj/auir" \
      org.label-schema.schema-version="1.0.0-rc1" \
      org.label-schema.vendor="Abdo Lab"
